version: "3.8"
services:
  postgres_test:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_USER=prisma
      - POSTGRES_PASSWORD=prisma
      - POSTGRES_DB=fofir_test
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5461:5432"

volumes:
  postgres:
