version: "3.8"
services:
  postgres:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_USER=prisma
      - POSTGRES_PASSWORD=prisma
      - POSTGRES_DB=fofir_dev
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5460:5432"

volumes:
  postgres:
